// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Bogus.DataSets;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace EasyImagery.Models;

public class Clinic
{
    public int Id { get; set; }

    [Required]
    [MaxLength(100)]
    public string? Name { get; set; }

    [MaxLength(500)]
    public string? Description { get; set; }

    [Display(Name = "Manager Id")]
    public string? ManagerId { get; set; }

    public ApplicationUser? Manager { get; set; }

    [Required]
    [MaxLength(200)]
    public string? Address { get; set; }

    public ICollection<ApplicationUser>? Physicians { get; set; }
}